// Generated by CoffeeScript 1.7.1
(function() {
  var Edge, Particle, Physics, RigidBody;

  Particle = (function() {
    function Particle() {
      this.position;
      this.oldPosition;
      this.acceleration;
    }

    return Particle;

  })();

  Edge = (function() {
    function Edge(v1, v2, length) {
      this.v1 = v1;
      this.v2 = v2;
      this.length = length;
    }

    return Edge;

  })();

  RigidBody = (function() {
    function RigidBody() {}

    return RigidBody;

  })();

  Physics = (function() {
    function Physics() {}

    Physics.prototype.updateVerlet = function() {};

    Physics.prototype.updateEdges = function() {};

    return Physics;

  })();

}).call(this);

//# sourceMappingURL=physics.map
