// Generated by CoffeeScript 1.7.1
this.Audio = (function() {
  function _Class() {
    this.effects = {};
    this.loadEffect('chomp');
    this.loadEffect('death');
    this.loadEffect('flipper');
    this.loadEffect('start');
  }

  _Class.prototype.loadEffect = function(name) {
    this.effects[name] = document.createElement('audio');
    this.effects[name].setAttribute('src', "assets/audio/" + name + ".wav");
    return this.effects[name].setAttribute('preload', 'auto');
  };

  return _Class;

})();

//# sourceMappingURL=Audio.map
