// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

this.Lancador = (function(_super) {
  __extends(_Class, _super);

  function _Class(mode) {
    this.mode = mode;
    _Class.__super__.constructor.call(this, 'lancador', 'lancador', 'assets/images/madeira.jpg');
  }

  _Class.prototype.animate = function(end) {
    this.end = end;
    this.animationTime = 0;
    this.animating = true;
    return this.duration = 150;
  };

  _Class.prototype.updateAnimation = function(elapsed) {
    var a, b, delta;
    this.animationTime += elapsed;
    if (this.animating) {
      delta = this.animationTime / this.duration;
      delta = Math.min(delta, 1.0);
      if (delta >= 1.0) {
        this.animating = false;
      }
      a = vec3.lerp(vec3.create(), vec3.create(), vec3.fromValues(0, 0, -0.1), delta);
      b = vec3.lerp(vec3.create(), vec3.fromValues(0, 0, -0.1), vec3.create(), delta);
      if (this.end) {
        return this.position = b;
      } else {
        return this.position = a;
      }
    }
  };

  return _Class;

})(ObjFile);

//# sourceMappingURL=Lancador.map
