// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.Paleta = (function(_super) {
    __extends(_Class, _super);

    _Class.LEFT = 0;

    _Class.RIGHT = 1;

    function _Class(mode) {
      var name;
      this.mode = mode;
      if (this.mode === Paleta.LEFT) {
        name = 'paleta-esq';
      } else {
        name = 'paleta-dir';
      }
      _Class.__super__.constructor.call(this, name, name, 'assets/images/madeira.jpg');
      this.animating = false;
    }

    _Class.prototype.animate = function(up, duration) {
      this.up = up;
      this.duration = duration != null ? duration : 1000;
      this.animationTime = 0;
      this.animating = true;
      return this.rotation = vec3.create();
    };

    _Class.prototype.updateAnimation = function(elapsed) {
      var delta, rot;
      this.animationTime += elapsed;
      if (this.animating) {
        delta = this.animationTime / this.duration;
        delta = Math.min(delta, 1.0);
        if (delta >= 1.0) {
          this.animating = false;
        }
        if (this.up) {
          if (this.mode === Paleta.LEFT) {
            rot = this.lerp(30, 0, delta);
          }
          if (this.mode === Paleta.RIGHT) {
            rot = this.lerp(-30, 0, delta);
          }
        } else {
          if (this.mode === Paleta.LEFT) {
            rot = this.lerp(0, 30, delta);
          }
          if (this.mode === Paleta.RIGHT) {
            rot = this.lerp(0, -30, delta);
          }
        }
        return this.rotation = vec3.fromValues(0, rot, 0);
      }
    };

    _Class.prototype.lerp = function(a, b, t) {
      return a + (b - a) * t || 0;
    };

    return _Class;

  })(ObjFile);

}).call(this);

//# sourceMappingURL=Paleta.map
