// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

this.Sphere = (function(_super) {
  __extends(_Class, _super);

  function _Class(radius) {
    this.radius = radius != null ? radius : 1.0;
    _Class.__super__.constructor.call(this, 'esfera', 'esfera', 'assets/images/foiled.jpg');
  }

  return _Class;

})(ObjFile);

//# sourceMappingURL=sphere.map
