// Generated by CoffeeScript 1.7.1
var Skybox, Sphere,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Sphere = (function(_super) {
  __extends(Sphere, _super);

  function Sphere(radius) {
    this.radius = radius != null ? radius : 1.0;
    Sphere.__super__.constructor.call(this, 'sphere-radius1', 'Icosphere_Icosphere');
  }

  return Sphere;

})(ObjFile);

window.Sphere = Sphere;

window.Skybox = Skybox = (function(_super) {
  __extends(Skybox, _super);

  function Skybox() {
    Skybox.__super__.constructor.call(this, 'skybox', 'skyboxGround_Circle');
  }

  return Skybox;

})(ObjFile);

//# sourceMappingURL=sphere.map
