// Generated by CoffeeScript 1.7.1

/*
Particle Physics

@author Anderson Freitas
 */

(function() {
  var Particle;

  Particle = (function() {
    function Particle(renderable, mass, radius) {
      this.renderable = renderable;
      this.mass = mass;
      this.radius = radius;
      this.renderable;
      this.mass;
      this.radius;
      this.velocity = vec3.create();
      this.forces = vec3.create();
    }

    Particle.prototype.applyForce = function(force) {
      this.forces = vec3.create();
      return vec3.add(this.forces, this.forces, force);
    };


    /*
    dt = time step
     */

    Particle.prototype.update = function(dt) {
      var acceleration, ds, dv;
      acceleration = vec3.create();
      dv = vec3.create();
      ds = vec3.create();
      vec3.div(acceleration, this.forces, this.mass);
      vec3.scale(dv, acceleration, dt);
      vec3.mul(ds, this.velocity, dt);
      vec3.add(this.renderable.position, this.renderable.position, ds);
      return this.speed = vec3.length(this.velocity);
    };

    return Particle;

  })();

  window.Particle = Particle;

}).call(this);

//# sourceMappingURL=Particle.map
